output: "{{.Dir}}/README.md"
format: github
header: |+
  [![Go Report Card](https://goreportcard.com/badge/github.com/eurielec/bulkerrs)](https://goreportcard.com/report/github.com/eurielec/bulkerrs)
  [![CircleCI](https://circleci.com/gh/Eurielec/bulkerrs.svg?style=svg)](https://circleci.com/gh/Eurielec/bulkerrs)

repository:
  url: https://github.com/eurielec/bulkerrs
  defaultBranch: master
  directory: .
